development:
  strategy: oauth
  oauth_consumer_key: "iOmGVNzw06wqCzYWJAAQ"
  oauth_consumer_secret: "Miz6DS11pF50tE7GUttFlRFQ4AvTQzza7lrfM5h7rI"
  base_url: "http://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: "iOmGVNzw06wqCzYWJAAQ"
  oauth_consumer_secret: "Miz6DS11pF50tE7GUttFlRFQ4AvTQzza7lrfM5h7rI"
  authorize_path: "/oauth/authenticate"  
  base_url: "http://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: "iOmGVNzw06wqCzYWJAAQ"
  oauth_consumer_secret: "Miz6DS11pF50tE7GUttFlRFQ4AvTQzza7lrfM5h7rI"
  authorize_path: "/oauth/authenticate"  
  base_url: "http://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
